In [1]:
#IMPORTING LIBRARIES

import os
working_directory = os.getcwd()
print(working_directory)
import pandas as pd

/Users/israahhanfa/IMBprojects

In [2]:
import numpy as np

In [5]:
#COLLECTING THE DATA 

data='HousePricePrediction.xlsx'

In [6]:
#READING THE DATA

df=pd.read_excel(data)

In [7]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [8]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (1.1.0)

In [35]:

df["SalePrice"]

0       208500.0
1       181500.0
2       223500.0
3       140000.0
4       250000.0
          ...
2914         NaN
2915         NaN
2916         NaN
2917         NaN
2918         NaN
Name: SalePrice, Length: 2919, dtype: float64

In [73]:
#DATA PRE_PROCESSING(removal of):
#a-null values
#b-duplicate values
#c-unnecessary columns

df["SalePrice"]= df["SalePrice"].fillna(df["SalePrice"].mean())

In [40]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [43]:
#dropping remaining null values
df=df.dropna()

In [44]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [45]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.1.3)
Requirement already satisfied: scipy>=1.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

In [48]:
#IMPORTING LabelEncoder

from sklearn.preprocessing import LabelEncoder

In [49]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [55]:
#encoding object columns (object-integer)

obj_cols=['MSZoning','LotConfig','BldgType','Exterior1st']
le=LabelEncoder()
for col in obj_cols:
    df[col]=le.fit_transform(df[col])

In [54]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.00000
1,1,20,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.00000
2,2,60,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.00000
3,3,70,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.00000
4,4,60,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,4,1936,4,3,7,1970,1970,5,0.0,546.0,180921.19589
2915,2915,160,4,1894,4,4,5,1970,1970,5,0.0,546.0,180921.19589
2916,2916,20,3,20000,4,0,7,1960,1996,12,0.0,1224.0,180921.19589
2917,2917,85,3,10441,4,0,5,1992,1992,6,0.0,912.0,180921.19589
2918,2918,60,3,9627,4,0,5,1993,1994,6,0.0,996.0,180921.19589

In [56]:
#features and target

X=df.drop(['SalePrice'],axis=1)
Y=df['SalePrice']

In [57]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.00000
1,1,20,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.00000
2,2,60,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.00000
3,3,70,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.00000
4,4,60,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,4,1936,4,3,7,1970,1970,5,0.0,546.0,180921.19589
2915,2915,160,4,1894,4,4,5,1970,1970,5,0.0,546.0,180921.19589
2916,2916,20,3,20000,4,0,7,1960,1996,12,0.0,1224.0,180921.19589
2917,2917,85,3,10441,4,0,5,1992,1992,6,0.0,912.0,180921.19589
2918,2918,60,3,9627,4,0,5,1993,1994,6,0.0,996.0,180921.19589

In [58]:
Y=df['SalePrice']

In [62]:
#TRAINING AND SPLITTING 

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test=train_test_split(X,Y,test_size=0.2, random_state=42, shuffle=True)

In [64]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,3,8450,4,0,5,2003,2003,12,0.0,856.0,208500.00000
1,1,20,3,9600,2,0,8,1976,1976,8,0.0,1262.0,181500.00000
2,2,60,3,11250,4,0,5,2001,2002,12,0.0,920.0,223500.00000
3,3,70,3,9550,0,0,5,1915,1970,13,0.0,756.0,140000.00000
4,4,60,3,14260,2,0,5,2000,2000,12,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,4,1936,4,3,7,1970,1970,5,0.0,546.0,180921.19589
2915,2915,160,4,1894,4,4,5,1970,1970,5,0.0,546.0,180921.19589
2916,2916,20,3,20000,4,0,7,1960,1996,12,0.0,1224.0,180921.19589
2917,2917,85,3,10441,4,0,5,1992,1992,6,0.0,912.0,180921.19589
2918,2918,60,3,9627,4,0,5,1993,1994,6,0.0,996.0,180921.19589

In [66]:
#SCALING DATA

from sklearn.preprocessing import StandardScaler

In [71]:
scalar= StandardScaler()
X_train_scaled=scalar.fit_transform(X_train)
X_test_scaled=scalar.transform(X_test)

In [72]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train_scaled, Y_train)

RandomForestRegressor(random_state=42)

In [74]:
#Prediction

Y_pred=model.predict(X_test_scaled)
df=Y_pred

df

In [76]:
#EVALUATION

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
print(f"MAE : {mean_absolute_error(Y_test, Y_pred):,.2f}")
print(f"R^2 : {r2_score(Y_test, Y_pred):,.3f}")

MAE : 12,041.58
R^2 : 0.811

In [82]:
#SINGLE PREDICTION EXAMPLE
input_df =(0,60,3,8450,4,0,5,2003,2003,12,0,0)
input_df_array = np.asarray(input_df).reshape(1, -1)
input_df_scaled = scalar.transform(input_df_array)
predicted_price = model.predict(input_df_scaled)
print(f"Predicted House Price : {predicted_price[0]:,.2f}")

Predicted House Price : 175,023.46

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(